package org.codenbug.purchase.domain.es;

public enum PurchaseEventType {
	CONFIRM_REQUESTED,
	PROCESSING_STARTED,
	HOLD_REJECTED,
	HOLD_ACQUIRED,
	PG_CONFIRM_REQUESTED,
	PG_CONFIRM_SUCCEEDED,
	PG_CONFIRM_FAILED,
	PAYMENT_COMPLETED
}
