package org.codenbug.purchase.domain.es;

public enum PurchaseEventType {
  PAYMENT_INITIATED,
  PAYMENT_CONFIRM_REQUESTED,
  CONFIRM_REQUESTED,
  PROCESSING_STARTED,
  PG_CONFIRM_REQUESTED,
  PAYMENT_COMPLETED,
  EVENT_CHANGED_PAYMENT_REJECTED,
  PG_CONFIRM_FAILED,
  PG_CONFIRM_SUCCEEDED,
  SEAT_PURCHASED,
  REFUND_COMPLETED
}
