server:
  port: 8080 # 게이트웨이는 8080 포트에서 실행됩니다.
  netty:
    connection-timeout: 30s
    max-connections: 2000
  reactor:
    netty:
      pool:
        max-connections: 2000
        max-idle-time: 30s


spring:
  profiles:
    include: secret
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        max-header-size: 16KB
        max-initial-line-length: 4KB
        pool:
          max-connections: 2000
          acquire-timeout: 30000
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:9001 # event 모듈이 실행될 주소
              predicates:
                - Path=/api/v1/auth/**
            - id: broker-service
              uri: lb://broker-service
              predicates:
                - Path=/api/v1/broker/**
            - id: main-service # 규칙의 고유 ID
              uri: http://localhost:9000 # user 모듈이 실행될 주소
              predicates:
                - Path=/api/v1/** # 이 경로 패턴의 요청이 오면 위 uri로 전달합니다.
          default-filters: AuthorizationFilter
  data:
    redis:
      host: localhost
      port: 6379
filter:
  whitelist:
    urls:
      - "/api/v1/auth/register"
      - "/api/v1/auth/login"
      - "/api/v1/auth/social/**"

logging:
  level:
    org.codenbug: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.resources: INFO
    org.springframework.scheduling: INFO
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.handler.predicate: DEBUG
