
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth.ticketon.site:9001 # event 모듈이 실행될 주소
              predicates:
                - Path=/api/v1/auth/**
            - id: broker-service
              uri: lb://broker-service
              predicates:
                - Path=/api/v1/broker/**
            - id: main-service # 규칙의 고유 ID
              uri: http://app.ticketon.site:9000 # user 모듈이 실행될 주소
              predicates:
                - Path=/api/v1/** # 이 경로 패턴의 요청이 오면 위 uri로 전달합니다.
          default-filters: AuthorizationFilter
  data:
    redis:
      host: 10.0.1.191
      port: 6379
filter:
  whitelist:
    urls:
      - "/api/v1/auth/register"
      - "/api/v1/auth/login"
      - "/api/v1/auth/social/**"
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.ticketon.site:8761/eureka/
    register-with-eureka: false
    fetch-registry: true