server:
  port: 8761 # Eureka 서버는 관례적으로 8761 포트를 사용합니다.

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # 자신은 등록하지 않음
    fetch-registry: false      # 레지스트리 정보를 가져오지 않음